sudo: required
language: generic

services:
  - docker

env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t klaidigorishti/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true klaidigorishti/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
